### ISSUE TITLE
Create Globe Experiment Finder

### ISSUE THREAD

**Issue by Maartenvm** [eWaterCycle/globe-experiment-finder#1]
Using Typescript, Angular 4 and Cesium, we create a globe visualization to display all of the watersheds of the world. This globe should have clickable watersheds, which display metadata of that watershed.

- [x] #8 Make globe visualization.
- [x] #2 Display watersheds.
- [x] #3 Meta-data info menu on the right side of the screen.
- [x] #4 (TEMP) YAML/JSON for Meta-data of watersheds.
- [ ] #5 (PERM) DB-solution for Meta-data of watersheds.
- [x] #6 CREATE EXPERIMENT button
- [ ] #8 Display controlled-vocabulary-keywords on meta-info tab
